services:
  cloudflare-warp:
    image: akimio/cloudflare-warp:latest
    container_name: cloudflare-warp
    restart: unless-stopped
    tty: true
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      # The IP address socat listens on inside the container.
      # Not necessary if using host network mode
      WARP_PROXY_LISTEN_IP: 0.0.0.0
      # The port exposed by socat for clients to connect to.
      # Not necessary if using host network mode
      WARP_PROXY_LISTEN_PORT: 4000
      # The local Cloudflare WARP proxy port socat forwards traffic to.
      # Not necessary if using host network mode
      WARP_PROXY_TARGET_PORT: 50000
      # Memory limit for warp-svc (optional).
      # Accepts K, M, G suffixes. Example: 512M
      # Omit to use the default 512M limit in the service unit.
      WARP_MEMORY_MAX: 512M
    volumes:
      - ./lib:/var/lib/cloudflare-warp
      - ./log:/var/log/cloudflare-warp
    tmpfs:
      - /run:exec,mode=0755
    ports:
      # Expose the proxy port to the host.
      # Not necessary if using host network mode
      - 4000:4000
