name: Check Cloudflare Warp Update

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      skip_check:
        description: "Skip the latest version check and force download release artifacts, release need to check latest version"
        required: false
        default: false
        type: boolean
      no_release:
        description: "Check for updates without creating a release"
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  check-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Install dependencies
        run: uv sync --frozen

      - name: Check version
        if: inputs.skip_check != 'true'
        id: check_version
        shell: bash
        run: |
          set -euo pipefail
          json_payload=$(uv run scripts/check_version.py)
          needs_sync=$(printf '%s\n' "$json_payload" | jq -r '.needs_sync')
          official_version=$(printf '%s\n' "$json_payload" | jq -r '.official_version')

          if [[ "$needs_sync" != "true" && "$needs_sync" != "false" ]]; then
            echo "Invalid needs_sync value: $needs_sync"
            exit 1
          fi

          echo "needs_sync=$needs_sync" >> "$GITHUB_OUTPUT"
          echo "official_version=$official_version" >> "$GITHUB_OUTPUT"

      - name: Download release artifacts
        if: steps.check_version.outputs.needs_sync == 'true' || inputs.skip_check == 'true'
        run: |
          uv run scripts/release.py

      - name: List release assets
        if: steps.check_version.outputs.needs_sync == 'true' || inputs.skip_check == 'true'
        run: |
          ls -la dist/release

      - name: Publish GitHub Release
        if: steps.check_version.outputs.needs_sync == 'true'  && inputs.no_release != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.check_version.outputs.official_version }}
          name: v${{ steps.check_version.outputs.official_version }}
          generate_release_notes: true
          files: |
            dist/release/*
